#ifndef __SET_THEORIC_T_C__H
#define __SET_THEORIC_T_C__H

#include <stdlib.h>

#include "src/tools_t/tools_t.h"

#define STRUCT_SET_THEORIC(type)\
  struct SET_THEORIC_##type{\
    type id;\
    type *set;};

STRUCT_SET_THEORIC(TYPE_U_CHAR)
STRUCT_SET_THEORIC(TYPE_U_INT)
STRUCT_SET_THEORIC(TYPE_U_LONG_INT)

typedef struct SET_THEORIC_TYPE_U_CHAR SET_THEORIC_TYPE_U_CHAR;
typedef struct SET_THEORIC_TYPE_U_INT SET_THEORIC_TYPE_U_INT;
typedef struct SET_THEORIC_TYPE_U_LONG_INT SET_THEORIC_TYPE_U_LONG_INT;

SET_THEORIC_TYPE_U_CHAR * CREATE_SET_THEORIC_TYPE_U_CHAR(TYPE_U_CHAR);
SET_THEORIC_TYPE_U_INT * CREATE_SET_THEORIC_TYPE_U_INT(TYPE_U_INT);
SET_THEORIC_TYPE_U_LONG_INT * CREATE_SET_THEORIC_TYPE_U_LONG_INT(TYPE_U_LONG_INT);

bool IS_SET_THEORIC_TYPE_U_CHAR(SET_THEORIC_TYPE_U_CHAR *st);
bool IS_SET_THEORIC_TYPE_U_INT(SET_THEORIC_TYPE_U_INT *st);
bool IS_SET_THEORIC_TYPE_U_LONG_INT(SET_THEORIC_TYPE_U_LONG_INT *st);



#endif /*__SET_THEORIC_T_C__H*/
